[hgh_pbe_hgh]
git-tree-sha1 = "be1b7c68c0d444fb29c3560ab3272eb0c3498534"
lazy = true

    [[hgh_pbe_hgh.download]]
    sha256 = "fdffdff49856d7eb200b302fbca8c10f7a805097e9d67c799ffee8e931e3a28e"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/hgh_pbe_hgh.tar.gz"

[hgh_pbe_upf]
git-tree-sha1 = "277efb8616e49b14d24db310e156a47cbf90d15f"
lazy = true

    [[hgh_pbe_upf.download]]
    sha256 = "e0cad7a76444b8de32504d6c8c8e2202a0d11e30ee5d691d45d94974943cff4b"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/hgh_pbe_upf.tar.gz"

[hgh_lda_hgh]
git-tree-sha1 = "8b15443d40af7e3a84f4e781330e67f307edbf16"
lazy = true

    [[hgh_lda_hgh.download]]
    sha256 = "3c674b8bf2cce081fd69fa0ea6c8fadec22fd278ed6f9346c3175295c302b797"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/hgh_lda_hgh.tar.gz"

[hgh_lda_upf]
git-tree-sha1 = "2ee02145aae92460f9a1cb51951c19fd577924ef"
lazy = true

    [[hgh_lda_upf.download]]
    sha256 = "1e9a17b42453b7430ec00ddecfd7dff7d1d80ed8db4c6e59afccf44979d151c5"
    url = "https://github.com/JuliaMolSim/PseudoLibrary/raw/main/artifacts/hgh_lda_upf.tar.gz"
